sudo: required
services:
    - docker

before_install:
    - docker build -t imkiransuvarna/CI_workflow_docker_travis_test -f ./client/Dockerfile.dev ./client

script:
    - dcocker run imkiransuvarna/CI_workflow_docker_travis_test npm test -- --coverage

after_success:
    - docker build -t imkiransuvarna/CI_workflow_docker_travis_client ./client
    - docker build -t imkiransuvarna/CI_workflow_docker_travis_nginx ./nginx
    - docker build -t imkiransuvarna/CI_workflow_docker_travis_server ./server
    - docker build -t imkiransuvarna/CI_workflow_docker_travis_worker ./worker
    #Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Push the images to docker
    - docker push imkiransuvarna/CI_workflow_docker_travis_client
    - docker push imkiransuvarna/CI_workflow_docker_travis_nginx
    - docker push imkiransuvarna/CI_workflow_docker_travis_server
    - docker push imkiransuvarna/CI_workflow_docker_travis_worker