language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t imkiransuvarna/ci_workflow_docker_travis_test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true imkiransuvarna/ci_workflow_docker_travis_test npm test

after_success:
    - docker build -t imkiransuvarna/ci_workflow_docker_travis_client ./client
    - docker build -t imkiransuvarna/ci_workflow_docker_travis_nginx ./nginx
    - docker build -t imkiransuvarna/ci_workflow_docker_travis_server ./server
    - docker build -t imkiransuvarna/ci_workflow_docker_travis_worker ./worker
    #Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Push the images to docker
    - docker push imkiransuvarna/ci_workflow_docker_travis_client
    - docker push imkiransuvarna/ci_workflow_docker_travis_nginx
    - docker push imkiransuvarna/ci_workflow_docker_travis_server
    - docker push imkiransuvarna/ci_workflow_docker_travis_worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: ci_workflow_docker_travis
    env: CiWorkflowDockerTravis-env
    bucket_name: elasticbeanstalk-ap-south-1-280685327061
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
