version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            POSTGRES_DB: 'db'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
        depends_on:
            - api
            - client
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /usr/app/complex/node_modules
            - ./server:/usr/app/complex
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /usr/app/complex/node_modules
            - ./client:/usr/app/complex
        stdin_open: true
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /usr/app/complex/node_modules
            - ./worker:/usr/app/complex
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379



